server:
  port: 8180
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    password: test
    username: test
    virtualHost: /delay
    listener:
      type: simple
      simple:
        default-requeue-rejected: false
        acknowledge-mode: manual